import React from "react";
import Header from "../components/Header";
import '../styles/TwoFectorAuth.css'
const TowFectorAuth = () => {
  const handleSubmit = (event) => {
    // Handle form submission
    event.preventDefault();
    // Add your form submission logic here
  };

  return (
    <div className="twofectorauthcontainermain">
      <Header routename="Two Factor Authentication" />
      <div className="twofectorauthbodycontainer">
        <div id="page">
          <div className="main_box_style" style={{ padding: "10px 25px" }}>
            <h3>
              <i
                className="fa-solid fa-unlock"
                style={{ color: "red", fontSize: "25px", float: "right" }}
              ></i>
              Setup Two-Factor Authentication:
            </h3>
            <br />

            <div style={{ paddingLeft: "20px" }}>
              <form onSubmit={handleSubmit}>
                <span style={{ fontSize: "13px" }}>
                  After activating the two factor authentication you will be
                  required to enter a verification code after each login to your
                  account.
                  <br />
                  <br />
                  There are two methods of authentication:
                  <br />
                  <br />
                  <input
                    type="radio"
                    name="typeof2FA"
                    value="1"
                    style={{ marginRight: "5px", verticalAlign: "text-top" }}
                  />
                  Email Verification (less secure method)
                  <br />
                  <br />
                  <input
                    type="radio"
                    name="typeof2FA"
                    value="2"
                    defaultChecked
                    style={{ marginRight: "5px", verticalAlign: "text-top" }}
                  />
                  Authenticator App Verification (recommended)
                  <div style={{ margin: "5px 23px" }}>
                    This code can be generated by any authenticator app
                    available via Google Play or Apple's App Store (for example:{" "}
                    <a
                      target="_blank"
                      href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&amp;hl=en&amp;gl=US"
                    >
                      Google Authenticator
                    </a>
                    ).
                    <br />
                    Once you sign up for the 2FA (two factor authentication) you
                    will receive a QR Code you can scan into the authenticator
                    app and once added you will be able to retrieve the
                    verification code via that app at any time.
                  </div>
                  <br />
                  <br />
                  Once you have activated the 2FA - the only way to login to
                  your account will be through the authentication method you've
                  selected (not even our support staff can assist you).
                  <br />
                  <br />
                  To activate two factor authentication on your account, please
                  enter your account's credentials:
                </span>
                <br />
                <br />
                <font className="bdv_000000_Bold_Text_10">UserName :</font>
                <br />
                <input
                  type="text"
                  className="form-field  towfectorinput"
                  size="51"
                  name="username"
                  id="username"
                />
                <br />
                <br />
                <font className="bdv_000000_Bold_Text_10">Password :</font>
                <br />
                <input 
                  type="password"
                  className="form-field towfectorinput"
                  size="51"
                  name="password"
                  id="password"
                />
                <input
                  id="g-recaptcha-response-workaround"
                  value=""
                  name="g-recaptcha-response"
                  type="hidden"
                />
                <input type="hidden" name="STEP1" value="1" className="twofectorinputmaininput" />
                <div
                  align="left"
                  style={{
                    transform: "scale(0.77)",
                    WebkitTransform: "scale(0.77)",
                    transformOrigin: "0 0",
                    WebkitTransformOrigin: "0 0",
                  }}
            
                  data-sitekey="6Lf-xT8UAAAAAGlAq_t7hB8wYLw_gbSJOTWhCtHM"
                  data-callback="recaptchaCallback"
                ></div>
                <br />
                <br />
                <div align="right" style={{ width: "385px" }}>
                  <input
                    type="submit"
                    value="Submit"
                    className="function-button"
                  />
                </div>
                <br />
              </form>
            </div>
          </div>
        </div>
        );
      </div>
    </div>
  );
};

export default TowFectorAuth;
